### ISSUE TITLE
[extended-monitoring] extended-monitoring-exporter pod crushed after reload at k8s 1.25

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#4276]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.44.4

### Expected Behavior

Working extended-monitoring-exporter pod

### Actual Behavior

In 1.25 after extended-monitoring-exporter pod reload we have error
```
[2023-04-03 04:52:54,667] - Starting metrics loop
[2023-04-03 04:52:54,668] - Starting server
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/extended-monitoring.py", line 293, in loop_get_metrics
    cls.get_metrics()
  File "/app/extended-monitoring.py", line 287, in get_metrics
    cls._response, quantity = _get_metrics()
  File "/app/extended-monitoring.py", line 266, in _get_metrics
    for annotated_object in chain.from_iterable(executor.map(_list_in_ns, ns_list)):
  File "/app/extended-monitoring.py", line 264, in _list_in_ns
    yield from _list_objects(executor, KUBERNETES_NAMESPACED_OBJECTS, ns)
  File "/app/extended-monitoring.py", line 244, in _list_objects
    yield from chain.from_iterable(executor.map(lambda k: k.list_threshold_annotated_objects(namespace), objects))
  File "/app/extended-monitoring.py", line 82, in list_threshold_annotated_objects
    for kube_object in cls.list(namespace, **cls.default_list_options):
  File "/app/extended-monitoring.py", line 224, in list
    return cls.api.list_namespaced_cron_job(namespace, **kwargs).items
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/batch_v1beta1_api.py", line 802, in list_namespaced_cron_job
    return self.list_namespaced_cron_job_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/batch_v1beta1_api.py", line 931, in list_namespaced_cron_job_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 377, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 244, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'fa7f55f4-e160-4b90-a9c0-1c0b4f927be1', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '39987b4b-4ed2-4d26-8eec-78e931c78a9d', 'X-Kubernetes-Pf-Prioritylevel-Uid': '7a064be5-722c-4de8-8deb-54cf114ecb2f', 'Date': 'Mon, 03 Apr 2023 04:52:54 GMT', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

```

### Steps To Reproduce

1. Switch kubernetes version to 1.25
2. Delete pod extended-monitoring-exporter in d8-monitoring namespace
3. After this extended-monitoring-exporter restarts permanently with error 400 (see log in above section).

**Comment by duckhawk** [comment]
Fix in #4292
