### ISSUE TITLE
[log-shipper] Vector crashes with error

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#737]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.30

### Expected Behavior

Vector agent works correctly

### Actual Behavior

```
kubectl -n d8-log-shipper logs vector-agent-ng4l9 -c vector
Feb 01 21:08:39.884  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
Feb 01 21:08:39.884  INFO vector::sources::host_metrics: PROCFS_ROOT is unset. Using default '/proc' for procfs root.
Feb 01 21:08:39.884  INFO vector::sources::host_metrics: SYSFS_ROOT is unset. Using default '/sys' for sysfs root.
Feb 01 21:08:39.884  INFO vector::app: Loading configs. path=[("/etc/vector/default/defaults.json", Some(Json)), ("/etc/vector/dynamic/vector.json", Some(Json))]
Feb 01 21:08:39.891  INFO vector::sources::kubernetes_logs: Obtained Kubernetes Node name to collect logs for (self). self_node_name="k-usa-spots-ba585432-9bb7d-dgbxl"
Feb 01 21:08:39.919  INFO vector::topology: Running healthchecks.
Feb 01 21:08:39.919  INFO vector::topology: Starting source. name="internal_metrics"
Feb 01 21:08:39.919  INFO vector::topology::builder: Healthcheck: Passed.
Feb 01 21:08:39.919  INFO vector::topology: Starting source. name="d8_cluster_source_flant-integration-d8-logs"
Feb 01 21:08:39.919  INFO vector::topology::builder: Healthcheck: Disabled.
Feb 01 21:08:39.920  INFO vector::topology: Starting transform. name="d8_tf_flant-integration-d8-logs_1"
Feb 01 21:08:39.922  INFO source{component_kind="source" component_name=d8_cluster_source_flant-integration-d8-logs component_type=kubernetes_logs}:file_server: file_source::checkpointer: Loaded checkpoint data.
Feb 01 21:08:39.920  INFO vector::topology: Starting transform. name="d8_tf_flant-integration-d8-logs_0"
Feb 01 21:08:39.920  INFO vector::topology: Starting sink. name="d8_cluster_sink_flant-integration-loki-storage"
Feb 01 21:08:39.920  INFO vector::topology: Starting sink. name="prometheus_sink"
Feb 01 21:08:39.920  INFO vector: Vector has started. version="0.14.0" arch="x86_64" build_id="none"
Feb 01 21:08:39.920  INFO vector::internal_events::api: API server running. address=0.0.0.0:8686 playground=off
thread 'tokio-runtime-worker' panicked at 'assertion failed: now >= lock.elapsed', /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/time/driver/mod.rs:267:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'assertion failed: now >= lock.elapsed', /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/time/driver/mod.rs:267:9
```
No pattern was found

### Additional Information

Maybe connected with https://github.com/tokio-rs/tokio/issues/3619

**Comment by nabokihms** [comment]
Fixed in:
* Tokio v1.11.0 - https://github.com/tokio-rs/tokio/pull/4083
* Vector v0.17

**Comment by nabokihms** [comment]
Related https://github.com/deckhouse/deckhouse/issues/1094
